const users = [
  {
    profilePicture: "https://randomuser.me/api/portraits/thumb/women/17.jpg",
    firstName: "Marlis",
    lastName: "Perrin",
    pronouns: "she/her",
    location: "Schangnau, Nidwalden, Switzerland",
    email: "marlis.perrin@example.com",
    username: "marlis",
    password: "master",
    meetingsAttended: 3,
    mentor: false,
    description:
      "Graduated a web development bootcamp and have no experience in the field and am looking for guidance into my new career",
    // desire: "looking for a job",
    gradyear: 2021,
    // isLookingForMentor: true,
    education: "UNC Coding Bootcamp",
    hoursSpentWithMentor: 7,
    details: ["JavaScript", "React", "TypeScript", "CSS"],
    currentPosition: "Store ",
    fieldOfInterest: "Web Development",
  },
  {
    profilePicture: "https://randomuser.me/api/portraits/thumb/men/11.jpg",
    firstName: "Julian",
    lastName: "Santana",
    pronouns: "they/them",
    location: "Gandía, Cataluña, Spain",
    email: "julian.santana@example.com",
    username: "jsant",
    password: "wilson",
    meetingsAttended: 0,
    mentor: false,
    description:
      "Bootcamp Graduate with a background in engineering looking for career guidance to leverage both of these passion",
    // desire: "looking for a job",
    gradyear: 2021,
    // isLookingForMentor: true,
    education: "UNC Coding Bootcamp",
    hoursSpentWithMentor: 13,
    details: [
      "Python",
      "C",
      "C#",
      "Java",
      "Angular",
      "SEO",
      "AEM",
      "ASP.NET",
      "Data Structures",
    ],
    currentPosition: "Civil Engineer",
    fieldOfInterest: "Web Development",
  },
  {
    profilePicture: "https://randomuser.me/api/portraits/thumb/women/60.jpg",
    firstName: "Solange",
    lastName: "Fogaça",
    pronouns: "she/her",
    location: "Coronel Fabriciano, Pernambuco, Brazil",
    email: "solange.fogaca@example.com",
    username: "solange",
    password: "2112",
    meetingsAttended: 7,
    mentor: true,
    description: "Software Engineer with 17 years experience in the field",
    gradYear: 2004,
    // desire:
    //   "To help young and old web developers advance in their skill sets and their careers",
    yearsExperience: 17,
    // isLookingForMentee: true,
    hoursSpentWithMentees: 27,
    hoursSpentThisWeek: 4,
    menteesAssigned: 2,
    details: ["JavaScript", "TypeScript", "CSS", "HTML", "SCSS"],
    currentPosition: "Developer",
    education: "UNC Coding Bootcamp",
  },
  {
    profilePicture: "https://randomuser.me/api/portraits/thumb/women/30.jpg",
    firstName: "Birgitta",
    lastName: "Hein",
    pronouns: "they/them",
    location: "Bad Wilsnack, Thüringen, Germany",
    email: "birgitta.hein@example.com",
    username: "birgitta",
    password: "foreplay",
    meetingsAttended: 9,
    mentor: false,
    description:
      "Graduated a web development bootcamp and have no experience in the field and am looking for guidance into my new career",
    // desire: "looking for a job",
    gradyear: 2021,
    // isLookingForMentor: true,
    education: "UNC Coding Bootcamp",
    hoursSpentWithMentor: 8,
    details: ["JavaScript", "React", "TypeScript", "CSS"],
    currentPosition: "Store ",
    fieldOfInterest: "Web Development",
  },
  {
    profilePicture: "https://randomuser.me/api/portraits/thumb/women/44.jpg",
    firstName: "Sienna",
    lastName: "Harris",
    pronouns: "she/her",
    location: "Invercargill, Taranaki, New Zealand",
    email: "sienna.harris@example.com",
    username: "siharr",
    password: "tractor",
    meetingsAttended: 4,
    mentor: false,
    description:
      "Looking to advance my career in the field of web development and need a mentor to help me on this path",
    // desire: "looking to advance my career",
    gradyear: 2019,
    // isLookingForMentor: true,
    education: "UNC Coding Bootcamp",
    hoursSpentWithMentor: 6,
    details: [
      "Python",
      "C",
      "WordPress",
      "ASP.NET",
      "Data Structures",
      "Alogrithms",
      "Management",
    ],
    currentPosition: "Developer",
    fieldOfInterest: "Web Development",
  },
  {
    profilePicture: "https://randomuser.me/api/portraits/thumb/men/85.jpg",
    firstName: "Neil",
    lastName: "Hicks",
    pronouns: "he/him",
    location: "St Albans, West Glamorgan, United Kingdom",
    email: "neil.hicks@example.com",
    username: "neihic",
    password: "windsor",
    meetingsAttended: 9,
    mentor: false,
    description:
      "Bootcamp Graduate with a background in engineering looking for career guidance to leverage both of these passion",
    // desire: "looking for a job",
    gradyear: 2021,
    // isLookingForMentor: true,
    education: "UNC Coding Bootcamp",
    hoursSpentWithMentor: 2,
    details: [
      "Python",
      "C",
      "C#",
      "Java",
      "Angular",
      "SEO",
      "AEM",
      "ASP.NET",
      "Data Structures",
    ],
    currentPosition: "Civil Engineer",
    fieldOfInterest: "Web Development",
  },
  {
    profilePicture: "https://randomuser.me/api/portraits/thumb/women/15.jpg",
    firstName: "Holly",
    lastName: "Davies",
    pronouns: "they/them",
    location: "Hamilton, Hawke'S Bay, New Zealand",
    email: "holly.davies@example.com",
    username: "holldav",
    password: "mann",
    meetingsAttended: 6,
    mentor: false,
    description:
      "Graduated a web development bootcamp and have no experience in the field and am looking for guidance into my new career",
    // desire: "looking for a job",
    gradyear: 2021,
    // isLookingForMentor: true,
    education: "UNC Coding Bootcamp",
    hoursSpentWithMentor: 6,
    details: ["JavaScript", "React", "TypeScript", "CSS"],
    currentPosition: "Store ",
    fieldOfInterest: "Web Development",
  },
  {
    profilePicture: "https://randomuser.me/api/portraits/thumb/women/96.jpg",
    firstName: "Katharina",
    lastName: "Sasse",
    pronouns: "she/her",
    location: "Egeln, Sachsen, Germany",
    email: "katharina.sasse@example.com",
    username: "ksass",
    password: "soccer",
    meetingsAttended: 7,
    mentor: true,
    description: "Software Engineer with 14 years experience in the field",
    gradYear: 2007,
    // desire:
    //   "To help young and old web developers advance in their skill sets and their careers",
    yearsExperience: 14,
    // isLookingForMentee: true,
    hoursSpentWithMentees: 10,
    hoursSpentThisWeek: 5,
    menteesAssigned: 3,
    details: ["JavaScript", "TypeScript", "CSS", "HTML", "SCSS"],
    currentPosition: "Developer",
    education: "UNC Coding Bootcamp",
  },
  {
    profilePicture: "https://randomuser.me/api/portraits/thumb/men/22.jpg",
    firstName: "Ege",
    lastName: "Eronat",
    pronouns: "he/him",
    location: "Burdur, Malatya, Turkey",
    email: "ege.eronat@example.com",
    username: "egeero",
    password: "mandrake",
    meetingsAttended: 0,
    mentor: false,
    description:
      "Graduated a web development bootcamp and have no experience in the field and am looking for guidance into my new career",
    // desire: "looking for a job",
    gradyear: 2021,
    // isLookingForMentor: true,
    education: "UNC Coding Bootcamp",
    hoursSpentWithMentor: 0,
    details: ["JavaScript", "React", "TypeScript", "CSS"],
    currentPosition: "Store ",
    fieldOfInterest: "Web Development",
  },
  {
    profilePicture: "https://randomuser.me/api/portraits/thumb/women/19.jpg",
    firstName: "Ndrea",
    lastName: "Barbosa",
    pronouns: "she/her",
    location: "Barbacena, Mato Grosso, Brazil",
    email: "ndrea.barbosa@example.com",
    username: "ndrea",
    password: "santa",
    meetingsAttended: 5,
    mentor: true,
    description: "Software Engineer with 20 years experience in the field",
    gradYear: 2001,
    // desire:
    //   "To help young and old web developers advance in their skill sets and their careers",
    yearsExperience: 20,
    // isLookingForMentee: true,
    hoursSpentWithMentees: 23,
    hoursSpentThisWeek: 6,
    menteesAssigned: 3,
    details: ["JavaScript", "TypeScript", "CSS", "HTML", "SCSS"],
    currentPosition: "Developer",
    education: "UNC Coding Bootcamp",
  },
  {
    profilePicture: "https://randomuser.me/api/portraits/thumb/men/43.jpg",
    firstName: "Edgar",
    lastName: "Morris",
    pronouns: "he/him",
    location: "Sunshine Coast, Victoria, Australia",
    email: "edgar.morris@example.com",
    username: "edmorris",
    password: "hottest",
    meetingsAttended: 9,
    mentor: false,
    description:
      "Looking to advance my career in the field of web development and need a mentor to help me on this path",
    // desire: "looking to advance my career",
    gradyear: 2019,
    // isLookingForMentor: true,
    education: "UNC Coding Bootcamp",
    hoursSpentWithMentor: 6,
    details: [
      "Python",
      "C",
      "WordPress",
      "ASP.NET",
      "Data Structures",
      "Alogrithms",
      "Management",
    ],
    currentPosition: "Developer",
    fieldOfInterest: "Web Development",
  },
  {
    profilePicture: "https://randomuser.me/api/portraits/thumb/women/79.jpg",
    firstName: "Mestan",
    lastName: "Abadan",
    pronouns: "she/her",
    location: "Zonguldak, Nevşehir, Turkey",
    email: "mestan.abadan@example.com",
    username: "mestan",
    password: "slowhand",
    meetingsAttended: 7,
    mentor: false,
    description:
      "Looking to advance my career in the field of web development and need a mentor to help me on this path",
    // desire: "looking to advance my career",
    gradyear: 2019,
    // isLookingForMentor: true,
    education: "UNC Coding Bootcamp",
    hoursSpentWithMentor: 11,
    details: [
      "Python",
      "C",
      "WordPress",
      "ASP.NET",
      "Data Structures",
      "Alogrithms",
      "Management",
    ],
    currentPosition: "Developer",
    fieldOfInterest: "Web Development",
  },
  {
    profilePicture: "https://randomuser.me/api/portraits/thumb/women/18.jpg",
    firstName: "Lisa",
    lastName: "Fields",
    pronouns: "she/her",
    location: "Swords, Leitrim, Ireland",
    email: "lisa.fields@example.com",
    username: "lisfie",
    password: "oregon",
    meetingsAttended: 4,
    mentor: false,
    description:
      "Bootcamp Graduate with a background in engineering looking for career guidance to leverage both of these passion",
    // desire: "looking for a job",
    gradyear: 2021,
    // isLookingForMentor: true,
    education: "UNC Coding Bootcamp",
    hoursSpentWithMentor: 7,
    details: [
      "Python",
      "C",
      "C#",
      "Java",
      "Angular",
      "SEO",
      "AEM",
      "ASP.NET",
      "Data Structures",
    ],
    currentPosition: "Civil Engineer",
    fieldOfInterest: "Web Development",
  },
  {
    profilePicture: "https://randomuser.me/api/portraits/thumb/men/96.jpg",
    firstName: "Fabio",
    lastName: "Laurent",
    pronouns: "he/him",
    location: "Toulouse, Paris, France",
    email: "fabio.laurent@example.com",
    username: "fablaur",
    password: "1952",
    meetingsAttended: 9,
    mentor: false,
    description:
      "Bootcamp Graduate with a background in engineering looking for career guidance to leverage both of these passion",
    // desire: "looking for a job",
    gradyear: 2021,
    // isLookingForMentor: true,
    education: "UNC Coding Bootcamp",
    hoursSpentWithMentor: 14,
    details: [
      "Python",
      "C",
      "C#",
      "Java",
      "Angular",
      "SEO",
      "AEM",
      "ASP.NET",
      "Data Structures",
    ],
    currentPosition: "Civil Engineer",
    fieldOfInterest: "Web Development",
  },
  {
    profilePicture: "https://randomuser.me/api/portraits/thumb/women/49.jpg",
    firstName: "Lauren",
    lastName: "Carvalho",
    pronouns: "she/her",
    location: "Abaetetuba, Mato Grosso do Sul, Brazil",
    email: "lauren.carvalho@example.com",
    username: "laurcarv",
    password: "patty",
    meetingsAttended: 8,
    mentor: true,
    description: "Software Engineer with 25 years experience in the field",
    gradYear: 1996,
    // desire:
    //   "To help young and old web developers advance in their skill sets and their careers",
    yearsExperience: 25,
    // isLookingForMentee: true,
    hoursSpentWithMentees: 28,
    hoursSpentThisWeek: 5,
    menteesAssigned: 2,
    details: ["JavaScript", "TypeScript", "CSS", "HTML", "SCSS"],
    currentPosition: "Developer",
    education: "UNC Coding Bootcamp",
  },
  {
    profilePicture: "https://randomuser.me/api/portraits/thumb/men/40.jpg",
    firstName: "Kaya",
    lastName: "Köybaşı",
    pronouns: "he/him",
    location: "Kocaeli, Mardin, Turkey",
    email: "kaya.koybasi@example.com",
    username: "kaykoy",
    password: "lions",
    meetingsAttended: 5,
    mentor: true,
    description: "Software Engineer with 27 years experience in the field",
    gradYear: 1994,
    // desire:
    //   "To help young and old web developers advance in their skill sets and their careers",
    yearsExperience: 27,
    // isLookingForMentee: true,
    hoursSpentWithMentees: 44,
    hoursSpentThisWeek: 3,
    menteesAssigned: 1,
    details: ["JavaScript", "TypeScript", "CSS", "HTML", "SCSS"],
    currentPosition: "Developer",
    education: "UNC Coding Bootcamp",
  },
  {
    profilePicture: "https://randomuser.me/api/portraits/thumb/women/39.jpg",
    firstName: "Misty",
    lastName: "Garrett",
    pronouns: "she/her",
    location: "Irvine, Oklahoma, United States",
    email: "misty.garrett@example.com",
    username: "misgarr",
    password: "metro",
    meetingsAttended: 1,
    mentor: false,
    description:
      "Looking to advance my career in the field of web development and need a mentor to help me on this path",
    // desire: "looking to advance my career",
    gradyear: 2019,
    // isLookingForMentor: true,
    education: "UNC Coding Bootcamp",
    hoursSpentWithMentor: 14,
    details: [
      "Python",
      "C",
      "WordPress",
      "ASP.NET",
      "Data Structures",
      "Alogrithms",
      "Management",
    ],
    currentPosition: "Developer",
    fieldOfInterest: "Web Development",
  },
  {
    profilePicture: "https://randomuser.me/api/portraits/thumb/women/24.jpg",
    firstName: "Mélina",
    lastName: "Perrin",
    pronouns: "she/her",
    location: "Montpellier, Alpes-Maritimes, France",
    email: "melina.perrin@example.com",
    username: "melperr",
    password: "trauma",
    meetingsAttended: 8,
    mentor: false,
    description:
      "Bootcamp Graduate with a background in engineering looking for career guidance to leverage both of these passion",
    // desire: "looking for a job",
    gradyear: 2021,
    // isLookingForMentor: true,
    education: "UNC Coding Bootcamp",
    hoursSpentWithMentor: 12,
    details: [
      "Python",
      "C",
      "C#",
      "Java",
      "Angular",
      "SEO",
      "AEM",
      "ASP.NET",
      "Data Structures",
    ],
    currentPosition: "Civil Engineer",
    fieldOfInterest: "Web Development",
  },
  {
    profilePicture: "https://randomuser.me/api/portraits/thumb/women/11.jpg",
    firstName: "Cleópatra",
    lastName: "Castro",
    pronouns: "she/her",
    location: "Águas Lindas de Goiás, Amapá, Brazil",
    email: "cleopatra.castro@example.com",
    username: "cleocas",
    password: "small",
    meetingsAttended: 1,
    mentor: false,
    description:
      "Looking to advance my career in the field of web development and need a mentor to help me on this path",
    // desire: "looking to advance my career",
    gradyear: 2019,
    // isLookingForMentor: true,
    education: "UNC Coding Bootcamp",
    hoursSpentWithMentor: 5,
    details: [
      "Python",
      "C",
      "WordPress",
      "ASP.NET",
      "Data Structures",
      "Alogrithms",
      "Management",
    ],
    currentPosition: "Developer",
    fieldOfInterest: "Web Development",
  },
  {
    profilePicture: "https://randomuser.me/api/portraits/thumb/men/53.jpg",
    firstName: "Connor",
    lastName: "Ruiz",
    pronouns: "he/him",
    location: "Ventura, South Carolina, United States",
    email: "connor.ruiz@example.com",
    username: "connrui",
    password: "13131313",
    meetingsAttended: 7,
    mentor: false,
    description:
      "Bootcamp Graduate with a background in engineering looking for career guidance to leverage both of these passion",
    // desire: "looking for a job",
    gradyear: 2021,
    // isLookingForMentor: true,
    education: "UNC Coding Bootcamp",
    hoursSpentWithMentor: 14,
    details: [
      "Python",
      "C",
      "C#",
      "Java",
      "Angular",
      "SEO",
      "AEM",
      "ASP.NET",
      "Data Structures",
    ],
    currentPosition: "Civil Engineer",
    fieldOfInterest: "Web Development",
  },
];
module.exports = users;
